dist: xenial
compiler:
- gcc
language: generic
services:
  - docker
env:
  global:
    - VERBOSE_OUTPUT='true'
    - CATKIN_PARALLEL_JOBS='-p1'
    - ROS_PARALLEL_JOBS='-j1'
matrix:
  include:
    - env: AFTER_INSTALL_TARGET_DEPENDENCIES='sh run_before.sh' UPSTREAM_WORKSPACE=debian ROS_DISTRO=melodic ROS_PYTHON_VERSION=2
    - env: AFTER_INSTALL_TARGET_DEPENDENCIESE='sh run_before.sh' UPSTREAM_WORKSPACE=debian ROS_DISTRO=melodic ROS_PYTHON_VERSION=3 ROS_FROM_SCRATCH=true
    - env: AFTER_INSTALL_TARGET_DEPENDENCIES='sh run_before.sh' UPSTREAM_WORKSPACE=debian ROS_DISTRO=kinetic ROS_PYTHON_VERSION=2
    - env: AFTER_INSTALL_TARGET_DEPENDENCIES='sh run_before.sh' UPSTREAM_WORKSPACE=debian ROS_DISTRO=noetic ROS_PYTHON_VERSION=3
install:
  - git clone --single-branch --branch master https://github.com/ros-industrial/industrial_ci.git
script:
  - .industrial_ci/travis.sh