dist: xenial
compiler:
- gcc
language: generic
services:
  - docker
env:
  global:
    - VERBOSE_OUTPUT='true'
matrix:
  include:
    - env: AFTER_INSTALL_TARGET_DEPENDENCIES='sh ci_config/run_before.sh' ROS_DISTRO=melodic
    - env: AFTER_INSTALL_TARGET_DEPENDENCIES='sh ci_config/run_before.sh' ROS_DISTRO=kinetic
    - env: AFTER_INSTALL_TARGET_DEPENDENCIES='sh ci_config/noetic_run_before_python3.sh' ROS_DISTRO=noetic
install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
  - source .industrial_ci/travis.sh