dist: xenial
compiler:
- gcc
language: generic
services:
  - docker
env:
  global:
    - VERBOSE_OUTPUT='true'
    - CATKIN_PARALLEL_JOBS='-p1'
    - ROS_PARALLEL_JOBS='-j1'
matrix:
  include:
    - env: AFTER_SCRIPT='sh run_tests.sh' AFTER_SETUP_TARGET_WORKSPACE='sh run_before.sh' UPSTREAM_WORKSPACE=debian ROS_DISTRO=melodic ROS_PYTHON_VERSION=2
    - env: AFTER_SCRIPT='sh run_tests.sh' AFTER_SETUP_TARGET_WORKSPACE='sh run_before.sh' UPSTREAM_WORKSPACE=debian ROS_DISTRO=melodic ROS_PYTHON_VERSION=3 ROS_FROM_SCRATCH=true
    - env: AFTER_SCRIPT='sh run_tests.sh' AFTER_SETUP_TARGET_WORKSPACE='sh run_before.sh' UPSTREAM_WORKSPACE=debian ROS_DISTRO=kinetic ROS_PYTHON_VERSION=2
install:
  - git clone --single-branch --branch python3-noetic https://github.com/ipa-mdl/industrial_ci.git .industrial_ci
script:
  - .industrial_ci/travis.sh